--- #YAML:1.0
name:                Runops-Trace
version:             0.06
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Digest::MD5:                   0
    Test::Simple:                  0.54
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
